spring.datasource.url=jdbc:oracle:thin:@//<host>:<port>/<service>
spring.datasource.username=<username>
spring.datasource.password=<Oracle-123>
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
